const express = require('express');
const router = express.Router();
const authMiddleware = require('../middleware/auth');
const ActivityLog = require('../models/ActivityLog');
const SessionLog = require('../models/SessionLog');
const { requireAdmin } = require('../utils/audit');

function escapeCsvCell(value) {
  if (value === undefined || value === null) return '';
  const text = String(value).replace(/"/g, '""');
  return `"${text}"`;
}

router.get('/', authMiddleware, requireAdmin, async (req, res) => {
  try {
    const {
      user,
      role,
      module: moduleFilter,
      action,
      severity,
      startDate,
      endDate,
      search,
      loginActivity,
      criticalOnly,
      page = 1,
      limit = 25,
      sortField = 'createdAt',
      sortOrder = 'desc'
    } = req.query;

    const filters = {};
    if (user) filters.userName = new RegExp(user, 'i');
    if (role) filters.role = role;
    if (moduleFilter) filters.module = moduleFilter;
    if (action) filters.action = new RegExp(action, 'i');
    if (severity) filters.severity = severity;
    if (loginActivity === 'true') filters.module = 'Auth';
    if (criticalOnly === 'true') filters.severity = 'CRITICAL';
    if (startDate || endDate) {
      filters.createdAt = {};
      if (startDate) filters.createdAt.$gte = new Date(startDate);
      if (endDate) filters.createdAt.$lte = new Date(new Date(endDate).setHours(23, 59, 59, 999));
    }
    if (search) {
      const regex = new RegExp(search, 'i');
      filters.$or = [
        { userName: regex },
        { role: regex },
        { module: regex },
        { action: regex },
        { description: regex },
        { ipAddress: regex },
        { deviceInfo: regex },
        { browserInfo: regex }
      ];
    }

    const pageNumber = Math.max(1, parseInt(page, 10));
    const pageSize = Math.max(1, Math.min(100, parseInt(limit, 10)));
    const skip = (pageNumber - 1) * pageSize;
    const sort = { [sortField]: sortOrder === 'asc' ? 1 : -1 };

    const [total, logs, activeSessionCount, criticalCount, failedLoginsCount, stockChangeCount, latestActivities] = await Promise.all([
      ActivityLog.countDocuments(filters),
      ActivityLog.find(filters).sort(sort).skip(skip).limit(pageSize).lean(),
      SessionLog.countDocuments({ logoutTime: null }),
      ActivityLog.countDocuments({ severity: 'CRITICAL' }),
      ActivityLog.countDocuments({ module: 'Auth', action: /login|logout|failed/i }),
      ActivityLog.countDocuments({ module: 'Pharmacy', action: /Stock|stock/i }),
      ActivityLog.find({}).sort({ createdAt: -1 }).limit(5).lean()
    ]);

    return res.json({
      logs,
      pagination: {
        total,
        page: pageNumber,
        limit: pageSize,
        pages: Math.ceil(total / pageSize)
      },
      summary: {
        activeSessionCount,
        criticalCount,
        failedLoginsCount,
        stockChangeCount,
        latestActivities
      }
    });
  } catch (err) {
    console.error('Audit route error:', err);
    res.status(500).json({ error: 'Failed to fetch audit logs', details: err.message });
  }
});

router.get('/export/csv', authMiddleware, requireAdmin, async (req, res) => {
  try {
    const { user, role, module: moduleFilter, action, severity, startDate, endDate, search, loginActivity, criticalOnly, sortField = 'createdAt', sortOrder = 'desc' } = req.query;
    const filters = {};
    if (user) filters.userName = new RegExp(user, 'i');
    if (role) filters.role = role;
    if (moduleFilter) filters.module = moduleFilter;
    if (action) filters.action = new RegExp(action, 'i');
    if (severity) filters.severity = severity;
    if (loginActivity === 'true') filters.module = 'Auth';
    if (criticalOnly === 'true') filters.severity = 'CRITICAL';
    if (startDate || endDate) {
      filters.createdAt = {};
      if (startDate) filters.createdAt.$gte = new Date(startDate);
      if (endDate) filters.createdAt.$lte = new Date(new Date(endDate).setHours(23, 59, 59, 999));
    }
    if (search) {
      const regex = new RegExp(search, 'i');
      filters.$or = [
        { userName: regex },
        { role: regex },
        { module: regex },
        { action: regex },
        { description: regex },
        { ipAddress: regex },
        { deviceInfo: regex },
        { browserInfo: regex }
      ];
    }

    const logs = await ActivityLog.find(filters).sort({ [sortField]: sortOrder === 'asc' ? 1 : -1 }).lean();

    const headerRows = [
      [
        'Wellness / Hospital System',
        'Audit Trail Report',
        `Generated By: ${req.user.email || req.user.role}`,
        `Generated At: ${new Date().toISOString()}`
      ],
      [`Filters: ${JSON.stringify(req.query)}`],
      []
    ];

    const columns = [
      'Date',
      'Time',
      'User',
      'Role',
      'Module',
      'Action',
      'Description',
      'Session Duration (sec)',
      'Severity',
      'IP Address',
      'Device',
      'Browser'
    ];

    const rows = logs.map(log => {
      const date = log.createdAt ? new Date(log.createdAt).toISOString().split('T')[0] : '';
      const time = log.createdAt ? new Date(log.createdAt).toISOString().split('T')[1].split('.')[0] : '';
      return [
        date,
        time,
        log.userName || log.userEmail || 'Unknown',
        log.role || 'Unknown',
        log.module || 'Unknown',
        log.action || '',
        log.description || '',
        log.sessionDuration ?? '',
        log.severity || 'INFO',
        log.ipAddress || '',
        log.deviceInfo || '',
        log.browserInfo || ''
      ];
    });

    const csvRows = [];
    headerRows.forEach((row) => {
      if (!row.length) {
        csvRows.push('');
        return;
      }
      csvRows.push(row.map(escapeCsvCell).join(','));
    });
    csvRows.push(columns.map(escapeCsvCell).join(','));
    rows.forEach((row) => csvRows.push(row.map(escapeCsvCell).join(',')));

    const csv = csvRows.join('\r\n');
    const filename = `audit-report-${new Date().toISOString().replace(/[:.]/g, '-')}.csv`;
    res.header('Content-Type', 'text/csv');
    res.header('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(csv);
  } catch (err) {
    console.error('Audit export error:', err);
    res.status(500).json({ error: 'Failed to export audit logs', details: err.message });
  }
});

module.exports = router;
